map_type: costmap

obstacle_range: 1.0 # 2.0
raytrace_range: 2.0 # 3.0

transform_tolerance: 0.5 # 0.0
min_particles: 50
max_particles: 500
update_min_d: 0.01
update_min_a: 0.005

robot_radius: 0.3 # 0.0
inflation_radius: 0.5 # 0.0
cost_scaling_factor: 5.0

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: hokuyo, data_type: LaserScan, topic: /my_robot/laser/scan, marking: true, clearing: true}
